---
application:
  name: "clients-api"
  project: "clients-api"
  organization: "QoveryCommunity"
routers:
- name: "main-clients-api"
  routes:
  - application_name: "clients-api"
    paths:
    - "/*"
